#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the list of staged files before linting
STAGED_FILES=$(git diff --cached --name-only)

# Run linting
pnpm lint
pnpm format

# Get the list of modified files after linting
MODIFIED_FILES=$(git diff --name-only)

# Find files that were both staged and modified
FILES_TO_COMMIT=$(comm -12 <(echo "$STAGED_FILES" | sort) <(echo "$MODIFIED_FILES" | sort))

if [ ! -z "$FILES_TO_COMMIT" ]; then
  # Add only the files that were both staged and modified
  echo "$FILES_TO_COMMIT" | xargs git add
  git commit --amend --no-edit
fi